### ISSUE TITLE
Add Visitors Badge !

### ISSUE THREAD

**Issue by rohank2502** [vinzvinci/vinzvinci#10]
-You can add a Visitor Badge.
-I liked the way you arranged the social link badges !!

**Comment by vinzvinci** [comment]
I'd remove that recently coz it can be fake from refreshing and you'll easily get views `(also heart it from @nhcarrigan)`. But I was looking to <a href="https://github.com/DenverCoder1">Jonah Lawrence</a> profile for the awesome GitHub Views badges.
~~-~~
Btw, thank you for reminding me that and opening issues here 😄.

**Comment by vinzvinci** [comment]
Hey, I decide not to include it anymore, I will close this now. Thanks for the suggestion.
